Updated scripts to better analyze the command line so that when arguments   are added it is easier to modify.
git-svn-id: https://svn.eiffel.com/eiffelstudio-public/trunk@67370 8089f293-4706-0410-a29e-feb5c42a2edf

diff --git a/Delivery/studio/spec/unix/finish_freezing b/Delivery/studio/spec/unix/finish_freezing
--- a/Delivery/studio/spec/unix/finish_freezing
+++ b/Delivery/studio/spec/unix/finish_freezing
@@ -1,9 +1,46 @@
 #!/bin/sh
 arg=none
+nologo=""
+ncpus=0
 
-echo "Eiffel C/C++ Compilation Tool - Version 6.0"
-echo "Copyright Eiffel Software 1985-2007. All Rights Reserved"
-echo
+if [ $# -gt 0 ]; then
+	while [ "$1" != "" ]; do
+		case "$1" in
+			"cecil" | "-cecil" | "-library") arg=$1 ;;
+			"-nproc")
+				shift
+				if [ $# -gt 0 ]; then
+						# Test if $1 is indeed an integer argument.
+					echo $1 | grep "[^0-9]" > /dev/null 2>&1
+					if [ "$?" -eq "0" ]; then
+						echo "Error: invalid value for nproc option"
+						echo "Option -nproc needs a non-negative integer argument"
+						exit 1
+					else
+						ncpus=$1
+					fi
+				else
+					echo "Usage: option -nproc needs a non-negative integer argument"
+					exit 1
+				fi
+				;;
+			"-x86") ;; # No effect on Unix yet
+			"-silent") ;; #Nothing anymore, kept for backward compatibility
+			"-nologo") nologo="nologo" ;;	# Keep or remove display of logo.
+			*)
+				echo "Usage: finish_freezing [-cecil | -library | -nproc VAL | -x86 | -silent ]"
+				exit 1
+				;;
+		esac
+		shift
+	done	
+fi
+
+if [ "$nologo" = "" ]; then
+	echo "Eiffel C/C++ Compilation Tool - Version 6.0"
+	echo "Copyright Eiffel Software 1985-2007. All Rights Reserved"
+	echo
+fi
 
 # default values for unix layout, so that no environment variables need to be set
 if [ -z "$ISE_EIFFEL" ]; then
@@ -43,16 +80,18 @@ else
 fi
 
 if $make --version 2>/dev/null | grep GNU >/dev/null 2>&1; then
-	case `uname` in
-		Darwin) ncpus=`sysctl -n hw.activecpu` ;;
-		Linux)
-			if [ -f /proc/cpuinfo ] ; then
-				ncpus=`grep -c '^processor[[:space:]]*:' /proc/cpuinfo`
-			fi
-			;;
-		SunOS) ncpus=`/usr/sbin/psrinfo | wc -l` ;;
-		IRIX*) ncpus=`hinv | awk '/^[0-9]+ [0-9]+ MHZ/ {print $1}'` ;;
-	esac
+	if [ ! $ncpus -ge 0 ]; then
+		case `uname` in
+			Darwin) ncpus=`sysctl -n hw.activecpu` ;;
+			Linux)
+				if [ -f /proc/cpuinfo ] ; then
+					ncpus=`grep -c '^processor[[:space:]]*:' /proc/cpuinfo`
+				fi
+				;;
+			SunOS) ncpus=`/usr/sbin/psrinfo | wc -l` ;;
+			IRIX*) ncpus=`hinv | awk '/^[0-9]+ [0-9]+ MHZ/ {print $1}'` ;;
+		esac
+	fi
 	if [ -z "$MAKELEVEL" -a -n "$ncpus" ]; then
 		if [ $ncpus -gt 1 ]; then
 			make_args="-j $ncpus"
@@ -62,14 +101,6 @@ if $make --version 2>/dev/null | grep GNU >/dev/null 2>&1; then
 		# time.
 	if [ -n "$DISTCC_COUNT" ]; then
 		make_args="-j $DISTCC_COUNT"
-	fi
-fi
-
-if [ $# -gt 0 ]; then
-	arg=$1
-	if [ "$arg" != cecil -a "$arg" != "-cecil" -a "$arg" != "-library" -a "$arg" != "-silent" ]; then
-		echo "Usage: finish_freezing [ -cecil | -library | -silent ]"
-		exit 1
 	fi
 fi
 
