Fix tabs vs spaces causing issue on Unix makefiles
git-svn-id: https://svn.eiffel.com/eiffelstudio-public/trunk@99998 8089f293-4706-0410-a29e-feb5c42a2edf

diff --git a/Src/C_library/libpng/Makefile.SH b/Src/C_library/libpng/Makefile.SH
--- a/Src/C_library/libpng/Makefile.SH
+++ b/Src/C_library/libpng/Makefile.SH
@@ -1,10 +1,10 @@
 case $CONFIG in
 '')
-        if test ! -f config.sh; then
-                (echo "Can't find config.sh."; exit 1)
-        fi 2>/dev/null
-        . ./config.sh
-        ;;
+	if test ! -f config.sh; then
+		(echo "Can't find config.sh."; exit 1)
+	fi 2>/dev/null
+	. ./config.sh
+	;;
 esac
 case "$0" in
 */*) cd `expr X$0 : 'X\(.*\)/'` ;;
@@ -19,5 +19,4 @@ $spitshell >>Makefile <<'!NO!SUBS!'
 
 
 main::
-        echo libpng
-
+	echo libpng
