New metaconfig (new version of metaconfig)
git-svn-id: https://svn.eiffel.com/eiffelstudio-public/trunk@949 8089f293-4706-0410-a29e-feb5c42a2edf

diff --git a/Src/bench/C/Configure b/Src/bench/C/Configure
--- a/Src/bench/C/Configure
+++ b/Src/bench/C/Configure
@@ -20,7 +20,7 @@
 
 # $Id$
 #
-# Generated on Fri Aug 12 14:10:11 PDT 1994 [metaconfig 3.0 PL31]
+# Generated on Mon Aug 29 13:55:47 PDT 1994 [metaconfig 3.0 PL35]
 
 cat >/tmp/c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -55,15 +55,27 @@ case "$0" in
 	;;
 esac
 
-: Sanity checks
-PATH=".:$PATH:/bin:/usr/bin:/usr/local/bin:/usr/ucb:/usr/local:/usr/lbin"
-PATH=$PATH:'/usr/5bin:/etc:/usr/gnu/bin:/usr/new:/usr/new/bin:/usr/nbin'
-PATH=$PATH:'/sys5.3/bin:/sys5.3/usr/bin:/bsd4.3/bin:/bsd4.3/usr/ucb'
-PATH=$PATH:'/bsd4.3/usr/bin:/usr/bsd:/bsd43/bin:/usr/ccs/bin'
-PATH=$PATH:'/etc:/usr/lib:/usr/ucblib:/lib:/usr/ccs/lib'
-PATH=$PATH:'/sbin:/usr/sbin:/usr/libexec'
+
+: Proper PATH setting
+paths='/bin /usr/bin /usr/local/bin /usr/ucb /usr/local /usr/lbin'
+paths=$paths:'/usr/5bin /etc /usr/gnu/bin /usr/new /usr/new/bin /usr/nbin'
+paths=$paths:'/sys5.3/bin /sys5.3/usr/bin /bsd4.3/bin /bsd4.3/usr/ucb'
+paths=$paths:'/bsd4.3/usr/bin /usr/bsd /bsd43/bin /usr/ccs/bin'
+paths=$paths:'/etc /usr/lib /usr/ucblib /lib /usr/ccs/lib'
+paths=$paths:'/sbin /usr/sbin /usr/libexec'
+
+for p in $paths
+do
+	case ":$PATH:" in
+	*:$p:*) ;;
+	*) test -d $p && PATH=$PATH:$p ;;
+	esac
+done
+
+PATH=.:$PATH
 export PATH
 
+: Sanity checks
 if test ! -t 0; then
 	echo "Say 'sh $me', not 'sh <$me'"
 	exit 1
@@ -205,6 +217,7 @@ d_bcmp=''
 d_bcopy=''
 d_bsdjmp=''
 d_bzero=''
+d_chown=''
 d_dup2=''
 d_eofpipe=''
 d_fcntl=''
@@ -248,7 +261,6 @@ d_socket=''
 d_sockpair=''
 sockethdr=''
 socketlib=''
-d_chown=''
 d_geteuid=''
 d_getgrgid=''
 d_getpwuid=''
@@ -354,6 +366,7 @@ package=''
 spackage=''
 d_maypanic=''
 pidtype=''
+prefix=''
 prototype=''
 ptrsize=''
 reg10=''
@@ -543,7 +556,7 @@ while test $# -gt 0; do
 		esac
 		shift
 		;;
-	-V) echo "$me generated by metaconfig 3.0 PL31." >&2
+	-V) echo "$me generated by metaconfig 3.0 PL35." >&2
 		exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -699,8 +712,8 @@ i_whoami=''
 xlibpth='/usr/lib/386 /lib/386'
 
 : general looking path for locating libraries
-glibpth="/usr/lib/large /lib /usr/lib $xlibpth /lib/large"
-glibpth="$glibpth /usr/lib/small /lib/small"
+glibpth="/lib/pa1.1 /usr/lib/large /lib /usr/lib $xlibpth"
+glibpth="$glibpth /lib/large /usr/lib/small /lib/small"
 glibpth="$glibpth /usr/ccs/lib /usr/ucblib /usr/local/lib /usr/shlib"
 
 : Private path used by Configure to find libraries.  Its value
@@ -984,7 +997,9 @@ if sh -c '#' >/dev/null 2>&1 ; then
 	spitshell=cat
 	echo " "
 	echo "Okay, let's see if #! works on this system..."
-	echo "#!/bin/cat" >try
+	xcat=/bin/cat
+	test -r $xcat || xcat=/usr/bin/cat
+	echo "#!$xcat" >try
 	$eunicefix try
 	chmod +x try
 	./try > today
@@ -992,7 +1007,7 @@ if sh -c '#' >/dev/null 2>&1 ; then
 		echo "It does."
 		sharpbang='#!'
 	else
-		echo "#! /bin/cat" > try
+		echo "#! $xcat" > try
 		$eunicefix try
 		chmod +x try
 		./try > today
@@ -1007,10 +1022,12 @@ if sh -c '#' >/dev/null 2>&1 ; then
 else
 	echo "Your sh doesn't grok # comments--I will strip them later on."
 	shsharp=false
+	cd ..
 	echo "exec grep -v '^[ 	]*#'" >spitshell
 	chmod +x spitshell
 	$eunicefix spitshell
 	spitshell=`pwd`/spitshell
+	cd UU
 	echo "I presume that if # doesn't work, #! won't work either!"
 	sharpbang=': use '
 fi
@@ -2316,6 +2333,9 @@ case "$ldflags" in
 	else
 		dflt='none'
 	fi
+	case "$ccflags" in
+	*-posix*) dflt="$dflt -posix" ;;
+	esac
 	;;
 *) dflt="$ldflags";;
 esac
@@ -2360,8 +2380,9 @@ done
 $cat <<'EOM'
 
 Some systems have incompatible or broken versions of libraries.  Among
-the directories listed in the question below, please remove the one
-you know not to be holding relevant libraries.  Say "none" for none.
+the directories listed in the question below, please remove any you
+know not to be holding relevant libraries, and add any that are needed.
+Say "none" for none.
 
 EOM
 case "$libpth" in
@@ -2682,7 +2703,7 @@ $echo $n ".$c"
 $grep fprintf libc.tmp > libc.ptf
 xscan='eval "<libc.ptf $com >libc.list"; $echo $n ".$c" >&4'
 xrun='eval "<libc.tmp $com >libc.list"; echo "done" >&4'
-if com="$sed -n -e 's/^.* [ADTS]  *_[_.]*//p' -e 's/^.* [ADTS] //p'";\
+if com="$sed -n -e 's/^.* [ADTSI]  *_[_.]*//p' -e 's/^.* [ADTSI] //p'";\
 	eval $xscan;\
 	$contains '^fprintf$' libc.list >/dev/null 2>&1; then
 		eval $xrun
@@ -3055,15 +3076,6 @@ eval $inlibc
 : see if chown exists
 set chown d_chown
 eval $inlibc
-: see if getpwuid exists
-set getpwuid d_getpwuid
-eval $inlibc
-: see if getgrgid exists
-set getgrgid d_getgrgid
-eval $inlibc
-: see if geteuid exists
-set geteuid d_geteuid
-eval $inlibc
 
 : see if this is a dirent system
 echo " "
@@ -3181,6 +3193,16 @@ case "$d_gettimeod$d_ftime" in
 	echo 'No ftime() nor gettimeofday() -- timing may be less accurate.' >&4
 	;;
 esac
+
+: see if getpwuid exists
+set getpwuid d_getpwuid
+eval $inlibc
+: see if getgrgid exists
+set getgrgid d_getgrgid
+eval $inlibc
+: see if geteuid exists
+set geteuid d_geteuid
+eval $inlibc
 
 : see if gethid exists
 set gethostid d_gethid
@@ -3975,30 +3997,50 @@ fi
 set d_time
 eval $setvar
 
+: define an is-a-typedef? function
+typedef='type=$1; var=$2; def=$3; shift; shift; shift; inclist=$@;
+case "$inclist" in
+"") inclist="sys/types.h";;
+esac;
+eval "val=\$$var";
+case "$val" in
+"")
+	$rm -f temp.c;
+	for inc in $inclist; do
+		echo "#include <$inc>" >>temp.c;
+	done;
+	$cppstdin $cppflags $cppminus < temp.c >temp.E 2>/dev/null;
+	if $contains $type temp.E >/dev/null 2>&1; then
+		eval "$var=$type";
+	else
+		eval "$var=$def";
+	fi;
+	$rm -f temp.?;;
+*) eval "$var=$val";;
+esac'
+
+: see if this is a sys/times.h system
+set sys/times.h i_systimes
+eval $inhdr
+
 : see if times exists
 echo " "
 if set times val -f d_times; eval $csym; $val; then
 	echo 'times() found.' >&4
 	d_times="$define"
-	case "$clocktype" in
-	'')
-		if $contains 'clock_t;' `./findhdr sys/types.h` >/dev/null 2>&1 ; then
-			dflt='clock_t';
-		elif $contains 'clock_t;' `./findhdr sys/times.h` >/dev/null 2>&1; then
-			dflt='clock_t';
-		else
-			dflt='long';
-		fi
-		;;
-	*)  dflt="$clocktype"
-		;;
+	inc=''
+	case "$i_systimes" in
+	"$define") inc='sys/times.h';;
 	esac
+	set clock_t clocktype long stdio.h sys/types.h $inc
+	eval $typedef
+	dflt="$clocktype"
 	echo " "
 	rp="What type is returned by times() on this sytem?"
 	. ./myread
 	clocktype="$ans"
 else
-	echo 'times() not found, hope that will do.' >&4
+	echo 'times() NOT found, hope that will do.' >&4
 	d_times="$undef"
 	clocktype='int'
 fi
@@ -4259,11 +4301,37 @@ else
 	afs=false
 fi
 
+: determine root of directory hierarchy where package will be installed.
+case "$prefix" in
+'')
+	dflt=`./loc . /usr/local /usr/local /local /opt /usr`
+	;;
+*)
+	dflt="$prefix"
+	;;
+esac
+$cat <<EOM
+
+By default, $package will be installed in $dflt/bin, manual
+pages under $dflt/man, etc..., i.e. with $dflt as prefix for
+all installation directories. Typically set to /usr/local, but you
+may choose /usr if you wish to install $package among your system
+binaries. If you wish to have binaries under /bin but manual pages
+under /usr/local/man, that's ok: you will be prompted separately
+for each of the installation directories, the prefix being only used
+to set defaults.
+
+EOM
+fn=d~
+rp='Installation prefix to use?'
+. ./getfile
+prefix="$ans"
+
 : determine where public executables go
 echo " "
 case "$bin" in
 '')
-	dflt=`./loc . /bin /usr/local/bin /usr/lbin /usr/local /usr/bin`
+	dflt="$prefix/bin"
 	;;
 *)
 	dflt="$bin"
@@ -4566,11 +4634,12 @@ esac
 echo "If you don't want the manual sources installed, answer 'none'."
 case "$mansrc" in
 '')
-	lookpath='/usr/local/man/man1 /usr/local/man/man1 /usr/man/manl'
+	lookpath="$prefix/man/man1 $prefix/man/u_man/man1 $prefix/man/l_man/man1"
+	lookpath="$lookpath /usr/local/man/man1 /usr/local/man/man1 /usr/man/manl"
 	lookpath="$lookpath /usr/man/local/man1 /usr/man/l_man/man1"
 	lookpath="$lookpath /usr/local/man/u_man/man1 /usr/local/man/l_man/man1"
 	lookpath="$lookpath /usr/man/man.L"
-	mansrc=`./loc . $lookpath`
+	mansrc=`./loc . $prefix/man/man1 $lookpath`
 	if $test -d "$mansrc"; then
 		dflt="$mansrc"
 	else
@@ -5018,16 +5087,9 @@ pagesize=$ans
 $rm -f page.c page
 
 : see what type pids are declared as in the kernel
-case "$pidtype" in
-'')
-	if $contains 'pid_t;' `./findhdr sys/types.h` >/dev/null 2>&1 ; then
-		dflt='pid_t';
-	else
-		dflt="int"
-	fi
-	;;
-*)  dflt="$pidtype";;
-esac
+set pid_t pidtype int stdio.h sys/types.h
+eval $typedef
+dflt="$pidtype"
 echo " "
 rp="What type are process ids on this system declared as?"
 . ./myread
@@ -5085,7 +5147,7 @@ echo "Checking how to generate random libraries on your machine..." >&4
 $cat >a.c <<EOP
 f() { exit(0); }
 EOP
-cc -c a.c >/dev/null 2>&1
+$cc -c a.c >/dev/null 2>&1
 ar rc ran.a a.o >/dev/null 2>&1
 $cat >b.c <<EOP
 main() { f(); }
@@ -5225,7 +5287,7 @@ rp="What is the return type of sbrk() on this system?"
 . ./myread
 sbrktype="$ans"
 
-: determine where public executables go
+: determine where public executable scripts go
 case "$scriptdir" in
 '')
 	dflt="$bin"
@@ -5233,6 +5295,7 @@ case "$scriptdir" in
 	$test -d /usr/share/scripts && dflt=/usr/share/scripts
 	$test -d /usr/share/bin && dflt=/usr/share/bin
 	$test -d /usr/local/script && dflt=/usr/local/script
+	$test -d $prefix/script && dflt=$prefix/script
 	;;
 *)  dflt="$scriptdir"
 	;;
@@ -5277,15 +5340,12 @@ $test "$xxx" && $cppstdin $cppminus $cppflags < $xxx >$$.tmp 2>/dev/null
 if $contains 'int.*\*[ 	]*signal' $$.tmp >/dev/null 2>&1 ; then
 	echo "You have int (*signal())() instead of void." >&4
 	val="$undef"
-	signal_t="int"
 elif $contains 'void.*\*[ 	]*signal' $$.tmp >/dev/null 2>&1 ; then
 	echo "You have void (*signal())() instead of int." >&4
 	val="$define"
-	signal_t="void"
 elif $contains 'extern[ 	]*[(\*]*signal' $$.tmp >/dev/null 2>&1 ; then
 	echo "You have int (*signal())() instead of void." >&4
 	val="$undef"
-	signal_t="int"
 else
 	case "$d_voidsig" in
 	'')
@@ -5293,41 +5353,42 @@ else
 		dflt=void
 		rp="What type does your signal handler return?"
 		. ./myread
-		signal_t="$ans"
-		;;
-	*) echo "As you already told me, signal handler returns $signal_t." >&4;;
-	esac
-	case "$signal_t" in
-	void) val="$define";;
-	*) val="$undef";;
+		case "$ans" in
+		v*) val="$define";;
+		*) val="$undef";;
+		esac;;
+	"$define")
+		echo "As you already told me, signal handler returns void." >&4;;
+	*)
+		echo "As you already told me, signal handler returns int." >&4;;
 	esac
 fi
 set d_voidsig
 eval $setvar
+case "$d_voidsig" in
+"$define") signal_t="void";;
+*) signal_t="int";;
+esac
 $rm -f $$.tmp
 
 : see what type uids are declared as in the kernel
+set uid_t uidtype xxx stdio.h sys/types.h
+eval $typedef
 case "$uidtype" in
-'')
-	if $contains 'uid_t;' `./findhdr sys/types.h` >/dev/null 2>&1 ; then
-		dflt='uid_t';
-	else
-		xxx=`./findhdr sys/user.h`
-		set `grep '_ruid;' "$xxx" 2>/dev/null` unsigned short
-		case $1 in
-		unsigned) dflt="$1 $2" ;;
-		*) dflt="$1" ;;
-		esac
-	fi
+xxx)
+	xxx=`./findhdr sys/user.h`
+	set `grep '_ruid;' "$xxx" 2>/dev/null` unsigned short
+	case $1 in
+	unsigned) dflt="$1 $2" ;;
+	*) dflt="$1" ;;
+	esac
 	;;
-*)  dflt="$uidtype";;
+*) dflt="$uidtype";;
 esac
 echo " "
 rp="What is the type for user ids returned by getuid()?"
 . ./myread
-val="$ans"
-set uidtype
-eval $setvar
+uidtype="$ans"
 
 : check for void type
 echo " "
@@ -5819,10 +5880,6 @@ fi
 set i_systimeb
 eval $setvar
 
-: see if this is a sys/times.h system
-set sys/times.h i_systimes
-eval $inhdr
-
 : see if this is a sys/un.h system
 set sys/un.h i_sysun
 eval $inhdr
@@ -5997,6 +6054,7 @@ d_bcmp='$d_bcmp'
 d_bcopy='$d_bcopy'
 d_bsdjmp='$d_bsdjmp'
 d_bzero='$d_bzero'
+d_chown='$d_chown'
 d_dup2='$d_dup2'
 d_eofpipe='$d_eofpipe'
 d_fcntl='$d_fcntl'
@@ -6040,7 +6098,6 @@ d_socket='$d_socket'
 d_sockpair='$d_sockpair'
 sockethdr='$sockethdr'
 socketlib='$socketlib'
-d_chown='$d_chown'
 d_geteuid='$d_geteuid'
 d_getgrgid='$d_getgrgid'
 d_getpwuid='$d_getpwuid'
@@ -6146,6 +6203,7 @@ package='$package'
 spackage='$spackage'
 d_maypanic='$d_maypanic'
 pidtype='$pidtype'
+prefix='$prefix'
 prototype='$prototype'
 ptrsize='$ptrsize'
 reg10='$reg10'
