*** empty log message ***
git-svn-id: https://svn.eiffel.com/eiffelstudio-public/trunk@472 8089f293-4706-0410-a29e-feb5c42a2edf

diff --git a/Src/bench/C/Configure b/Src/bench/C/Configure
--- a/Src/bench/C/Configure
+++ b/Src/bench/C/Configure
@@ -20,7 +20,7 @@
 
 # $Id$
 #
-# Generated on Tue Jan 18 10:19:10 PST 1994 [metaconfig 3.0 PL15]
+# Generated on Fri Feb 11 16:08:55 PST 1994 [metaconfig 3.0 PL22]
 
 cat >/tmp/c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -216,6 +216,7 @@ d_readdir=''
 d_rename=''
 d_rmdir=''
 d_rusage=''
+d_sbrk=''
 d_bsdpgrp=''
 d_setpgrp=''
 d_siglist=''
@@ -265,7 +266,6 @@ i_sysioctl=''
 i_syssockio=''
 i_sysndir=''
 i_sysresrc=''
-i_sysselct=''
 i_syssock=''
 i_systimeb=''
 i_systimes=''
@@ -277,6 +277,7 @@ i_systime=''
 i_systimek=''
 i_time=''
 timeincl=''
+i_tmvlsyss=''
 i_varargs=''
 i_varhdr=''
 intsize=''
@@ -334,6 +335,7 @@ reg7=''
 reg8=''
 reg9=''
 registers=''
+sbrksmart=''
 sbrktype=''
 installscript=''
 scriptdir=''
@@ -477,7 +479,7 @@ while test $# -gt 0; do
 	-s) shift; silent=true;;
 	-E) shift; alldone=exit;;
 	-S) shift; extractsh=true;;
-	-V) echo "Configure generated by metaconfig 3.0 PL15." >&2
+	-V) echo "Configure generated by metaconfig 3.0 PL22." >&2
 		exit 0;;
 	--) break;;
 	-*) echo "Configure: unknown option $1" >&2; shift; error=true;;
@@ -528,7 +530,7 @@ true)
 esac
 
 : set package name
-package=Eiffel-3
+package=Eiffel3
 
 : Eunice requires " " instead of "", can you believe it
 echo " "
@@ -568,6 +570,7 @@ attrlist="$attrlist __unix__ vax venix xenix z8000"
 : no include file wanted by default
 inclwanted=''
 
+i_sysselct=''
 i_whoami=''
 : change the next line if compiling for Xenix/286 on Xenix/386
 xlibpth='/usr/lib/386 /lib/386'
@@ -643,7 +646,7 @@ THIS PACKAGE SEEMS TO BE INCOMPLETE.
 You have the option of continuing the configuration process, despite the
 distinct possibility that your kit is damaged, by typing 'y'es.  If you
 do, don't blame me if something goes wrong.  I advise you to type 'n'o
-and contact the author (eiffel@eiffel.com).
+and contact the author (xavierl@vienna.eiffel.com).
 
 EOM
 		echo $n "Continue? [n] $c" >&4
@@ -785,7 +788,7 @@ if $needman; then
 	cat <<EOH
  
 This installation shell script will examine your system and ask you questions
-to determine how the Eiffel-3 package should be installed. If you get
+to determine how the Eiffel3 package should be installed. If you get
 stuck on a question, you may use a ! shell escape to start a subshell or
 execute a command.  Many of the questions will have default answers in square
 brackets; typing carriage return will give you the default.
@@ -821,7 +824,7 @@ EOH
 
 Much effort has been expended to ensure that this shell script will run on any
 Unix system.  If despite that it blows up on yours, your best bet is to edit
-Configure and run it again.  Also, let me (eiffel@eiffel.com)
+Configure and run it again.  Also, let me (xavierl@vienna.eiffel.com)
 know how I blew it.  If you can't run Configure for some reason, you'll have to
 generate a config.sh file by hand.
 
@@ -1057,6 +1060,8 @@ esac
 case "$config_sh" in
 '')
 myuname=`( ($uname -a) 2>/dev/null || hostname) 2>&1`
+myuname=`echo $myuname | $sed -e 's/^[^=]*=//' | \
+	tr '[A-Z]' '[a-z]' | tr '\012' ' '`
 dflt=n
 if test "$fastread" = yes; then
 	dflt=y
@@ -1100,7 +1105,7 @@ EOM
 	cd hints; ls -C *.sh | $sed 's/\.sh/   /g' >&4
 	dflt=''
 	: Half the following guesses are probably wrong... If you have better
-	: tests or hints, please send them to eiffel@eiffel.com
+	: tests or hints, please send them to xavierl@vienna.eiffel.com
 	: The metaconfig authors would also appreciate a copy...
 	$test -f /irix && dflt="$dflt sgi"
 	$test -f /xenix && dflt="$dflt sco_xenix"
@@ -1110,7 +1115,8 @@ EOM
 	$test -d /NextApps && test -f /usr/adm/software_version && dflt="$dflt next"
 	$test -d /usr/include/minix && dflt="$dflt minix"
 	if $test -f $uname; then
-		set `$uname -a | tr '[A-Z]' '[a-z]'`
+		set X $myuname
+		shift
 
 		$test -f $5.sh && dflt="$dflt $5"
 
@@ -4140,7 +4146,7 @@ $cat <<EOM
 
 $package has manual pages available in source form.
 EOM
-case "$nroff" in
+case "$_nroff" in
 nroff)
 	echo "However, you don't have nroff, so they're probably useless to you."
 	case "$mansrc" in
@@ -4742,6 +4748,60 @@ $awk "BEGIN { for (i=1; i<=$registers; i++) printf \"reg%d=register\n\", i}" \
 . ./.foo
 $rm -f .foo
 
+: see if sbrk exists
+set sbrk d_sbrk
+eval $inlibc
+
+: see if sbrk can release core to the kernel
+echo " "
+case "$d_sbrk" in
+"$define")
+	echo "Let's see if your sbrk() is smart enough to release core..." >&4
+	$cat > sbrk.c <<'EOC'
+#define INC 256		/* Small enough to be less than a page size */
+
+main()
+{
+	char *obrk = (char *) sbrk(0);
+	char *nbrk;
+
+	nbrk = (char *) sbrk(INC);
+	if (nbrk == (char *) -1)
+		exit(1);	/* Not enough memory */
+	if (nbrk != obrk)
+		exit(2);	/* Unreliable sbrk() */
+	nbrk = sbrk(-INC);
+	if (nbrk == (char *) -1)
+		exit(3);	/* May have understood negative arg as huge positive */
+	if (obrk != (char *) sbrk(0))
+		exit(4);	/* Not smart, definitely */
+
+	exit(0);		/* Ok */
+}
+EOC
+	sbrksmart="$undef"
+	dumb='-- assuming dumb sbrk().'
+	if $cc $ccflags -o sbrk sbrk.c $libs >/dev/null 2>&1; then
+		./sbrk >/dev/null 2>&1
+		case $? in
+		0) sbrksmart="$define"
+			echo "Yes, it can be used with negative values." ;;
+		1) echo "Sorry, not enough memory $dumb" ;;
+		2) echo "No it's not, and besides it seems to be buggy..." ;;
+		3) echo "No, it fails with negative values." ;;
+		4) echo "Nope, your sbrk() is too dumb." ;;
+		*) echo "Err... Unexpected result $dumb" ;;
+		esac
+	else
+		echo "(Could not compile test program $dumb)"
+	fi
+	;;
+*)
+	echo "Since you don't have sbrk(), let's forget about the smart test!"
+	;;
+esac
+$rm -f sbrk sbrk.* core
+
 : see what type sbrk is declared as in the kernel
 case "$sbrktype" in
 '')
@@ -5103,10 +5163,6 @@ eval $inhdr
 set sys/resource.h i_sysresrc
 eval $inhdr
 
-: see if sys/select.h has to be included
-set sys/select.h i_sysselct
-eval $inhdr
-
 : see if this is a sys/socket.h system
 set sys/socket.h i_syssock
 eval $inhdr
@@ -5220,6 +5276,20 @@ eval $inhdr
 set sys/un.h i_sysun
 eval $inhdr
 
+: see if sys/select.h has to be included
+xxx=`./findhdr sys/select.h`
+if $test "$xxx"; then
+    if $contains 'timeval.*{' $xxx >/dev/null 2>&1; then
+        val="$define"
+        echo "You have struct timeval defined in <sys/select.h>." >&4
+	else
+		val="$undef"
+    fi
+else
+    val="$undef"
+fi
+set i_tmvlsyss
+eval $setvar
 : see if this is a varargs system
 echo " "
 if $test `./findhdr varargs.h`; then
@@ -5294,7 +5364,8 @@ case "$i_varhdr" in
 '')
 echo "I could not find the definition for va_dcl... You have problems..." >&4
 	;;
-*) echo "We'll include <$i_varhdr> to get va_dcl definition." >&4;;
+*) echo "We'll include <$i_varhdr> to get va_dcl definition." >&4
+echo "The standard unit (dist3.0 p22)does NOT work correctly (prototypes ...)">&4;;
 esac
 $rm -f varargs*
 
@@ -5471,6 +5542,7 @@ d_readdir='$d_readdir'
 d_rename='$d_rename'
 d_rmdir='$d_rmdir'
 d_rusage='$d_rusage'
+d_sbrk='$d_sbrk'
 d_bsdpgrp='$d_bsdpgrp'
 d_setpgrp='$d_setpgrp'
 d_siglist='$d_siglist'
@@ -5520,7 +5592,6 @@ i_sysioctl='$i_sysioctl'
 i_syssockio='$i_syssockio'
 i_sysndir='$i_sysndir'
 i_sysresrc='$i_sysresrc'
-i_sysselct='$i_sysselct'
 i_syssock='$i_syssock'
 i_systimeb='$i_systimeb'
 i_systimes='$i_systimes'
@@ -5532,6 +5603,7 @@ i_systime='$i_systime'
 i_systimek='$i_systimek'
 i_time='$i_time'
 timeincl='$timeincl'
+i_tmvlsyss='$i_tmvlsyss'
 i_varargs='$i_varargs'
 i_varhdr='$i_varhdr'
 intsize='$intsize'
@@ -5589,6 +5661,7 @@ reg7='$reg7'
 reg8='$reg8'
 reg9='$reg9'
 registers='$registers'
+sbrksmart='$sbrksmart'
 sbrktype='$sbrktype'
 installscript='$installscript'
 scriptdir='$scriptdir'
