Improved installation script based on bug#14245.
git-svn-id: https://svn.eiffel.com/eiffelstudio-public/trunk@73758 8089f293-4706-0410-a29e-feb5c42a2edf

diff --git a/Delivery/make_install b/Delivery/make_install
--- a/Delivery/make_install
+++ b/Delivery/make_install
@@ -4,17 +4,53 @@ echo Welcome to the EiffelStudio installer
 
 ERROR_ENV=""
 if [ ! "$ISE_EIFFEL" ]; then
-	echo "The environment variable ISE_EIFFEL should be set to the directory where EiffelStudio is installed (typically the current directory: `pwd`)"
+	echo "The environment variable ISE_EIFFEL should be set to the directory where"
+	echo "EiffelStudio is installed (typically the current directory)."
+	echo "Current directory is `pwd`"
 	ERROR_ENV=TRUE
 fi
 if [ ! "$ISE_PLATFORM" ]; then
-	echo The environment variable ISE_PLATFORM should be set to one of these values, depending on your platform:
-	echo linux-x86, linux-x86-64 irix-mips, irix-mips-64, solaris-sparc, solaris-sparc-64, solaris-x86, ...
+	echo "The environment variable ISE_PLATFORM should be set to one of the following values,"
+	echo "depending on your platform:"
+	echo " "
+	echo "   freebsd-x86"
+	echo "   freebsd-x86-64"
+	echo "   irix-mips"
+	echo "   irix-mips-64"
+	echo "   linux-sparc"
+	echo "   linux-x86"
+	echo "   linux-x86-64"
+	echo "   macosx-ppc"
+	echo "   macosx-x86"
+	echo "   openbsd-x86"
+	echo "   solaris-sparc"
+	echo "   solaris-sparc-64"
+	echo "   solaris-x86"
+	echo "   solaris-x86-64"
+	echo " "
 	ERROR_ENV=TRUE
 fi
 if [ "$ERROR_ENV" = "TRUE" ]; then
 	echo "When the needed environment variable(s) are set, launch $0 again."
-	exit
+	exit 1
+fi
+
+ERROR_COMPILER=""
+compiler="$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/ec"
+if [ ! -f "$compiler" ]; then
+	echo "Eiffel compiler $compiler not found or not a plain file"
+	ERROR_COMPILER=TRUE
+elif [ ! -x "$compiler" ]; then
+	echo "Eiffel compiler $compiler not executable"
+	ERROR_COMPILER=TRUE
+elif [ ! -s "$compiler" ]; then
+	echo "Eiffel compiler $compiler has size 0"
+	ERROR_COMPILER=TRUE
+fi    
+if [ "$ERROR_COMPILER" = "TRUE" ]; then
+	echo "Cannot precompile due to missing or nonexecutable compiler."
+	echo "Please check that EiffelStudio was installed correctly."
+	exit 1
 fi
 
 echo "Do you want to precompile EiffelBase (required to compile examples) ? [y/n]"
@@ -25,23 +61,31 @@ read prec_vision2
 INIT_DIR=`pwd`
 
 if [ "$prec_base" != "n" ]; then
-	echo Precompile EiffelBase
+	echo " "
+	echo Precompiling EiffelBase
 	cd $ISE_EIFFEL/precomp/spec/$ISE_PLATFORM
-	$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/ec -precompile -config base.ecf -c_compile -clean
+	$compiler -precompile -config base.ecf -c_compile -clean
+	echo " "
+	echo Precompiling multithreaded EiffelBase
+	$compiler -precompile -config base-mt.ecf -c_compile -clean
 fi
 if [ "$prec_vision2" = "y" ]; then
 	if which pkg-config > /dev/null 2>&1 ; then
 		if pkg-config --atleast-version=2.4 gtk+-2.0 ; then
-			echo Precompile EiffelVision
+			echo " "
+			echo Precompiling EiffelVision
 			cd $ISE_EIFFEL/precomp/spec/$ISE_PLATFORM
-			$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin/ec -precompile -config vision2.ecf -c_compile -clean
+			$compiler -precompile -config vision2.ecf -c_compile -clean
+			echo " "
+			echo Precompiling multithreaded EiffelVision
+			$compiler -precompile -config vision2-mt.ecf -c_compile -clean
 		else
-			echo "GTK 2.4 does not seem to be installed"
-			echo "Precompilation of EiffelVision interrupted."
+			echo "GTK version 2.4 or later does not seem to be installed"
+			echo "Precompilation of EiffelVision skipped."
 		fi
 	else
-		echo "GTK 2.4 does not seem to be installed"
-		echo "Precompilation of EiffelVision interrupted."
+		echo "pkg-config does not seem to be installed"
+		echo "Precompilation of EiffelVision skipped."
 	fi
 fi
 
